# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-28 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20171128_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.TextField(max_length=300, verbose_name='\u8bfe\u7a0b\u63cf\u8ff0'),
        ),
    ]
